from setuptools import setup, find_packages

setup(
    name='project_pokereader',
    version='1.0.0',
    description='A comprehensive Python package for machine learning model deployment with Streamlit, Docker, FastAPI, and Google Cloud Platform (GCP).',
    author='Yuri, Estelle, Emilia, Alex',
    author_email='alex.tm.chiu@gmail.com',
    packages=find_packages(),
    install_requires=[
        "httpx==0.27.0",
        "ipykernel==6.29.4",
        "ipython==8.24.0",
        "matplotlib==3.9.0",
        "matplotlib-inline==0.1.7",
        "numpy==1.26.4",
        "pandas==2.2.2",
        "pip==24.0",
        "pytesseract==0.3.10",
        "requests==2.31.0",
        "scikit-learn==1.4.2",
        "tensorflow==2.16.1",
        "pyocr==0.8.5",
        "streamlit==1.35.0",
        "opencv-python-headless",
        "async-lru==2.0.4",
        "joblib==1.4.2",
        "psutil==5.9.8",
        "pycparser==2.22",
        "pyparsing==3.1.2",
        "python-dateutil==2.9.0.post0",
        "PyYAML==6.0.1",
        "scipy==1.13.0",
        "fastapi==0.111.0",
        "fastapi-cli==0.0.4",
        "uvicorn==0.29.0"
        ])
